providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = [
  "echo '--- INSTALL PHASE ---'",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "echo '--- BUILD PHASE ---'",
  "pnpm build"
]

[start]
cmd = "pnpm db:push && pnpm start"
